version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: rails s
    volumes:
      - .:/test_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgres://postgres@db/test_api_production
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
      - WEB_CONCURRENCY=$WEB_CONCURRENCY
      - RAILS_MAX_THREADS=$RAILS_MAX_THREADS
      - RAILS_LOG_TO_STDOUT=true